# Generated by Django 3.2.1 on 2022-03-10 15:43

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_no', models.CharField(max_length=10)),
                ('isAgent', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('state', models.CharField(default='', max_length=150)),
                ('state_desc', models.CharField(max_length=10000)),
                ('details', models.CharField(max_length=10000)),
                ('agent_company_name', models.CharField(default='', max_length=150)),
                ('agent_company_desc', models.CharField(default='', max_length=1000)),
                ('img1', models.CharField(default='', max_length=10000)),
                ('img2', models.CharField(max_length=10000)),
                ('img3', models.CharField(max_length=10000)),
                ('img4', models.CharField(max_length=10000)),
                ('price', models.IntegerField(default=0)),
                ('seat', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.BigIntegerField()),
                ('cvv_no', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('name', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mytravelloo.user')),
                ('company_name', models.CharField(default='', max_length=150)),
                ('company_desc', models.CharField(default='', max_length=1000)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('mytravelloo.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mytravelloo.user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('mytravelloo.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=500)),
                ('name', models.CharField(default='', max_length=150)),
                ('age', models.IntegerField(default=18)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.BigIntegerField()),
                ('address', models.CharField(default='', max_length=500)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('pincode', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('time_of_booking', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytravelloo.destination')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytravelloo.agent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytravelloo.customer')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytravelloo.agent'),
        ),
    ]
