# Generated by Django 3.2.1 on 2022-04-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytravelloo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Agent'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer'},
        ),
    ]
